name: flutter_application_kesehatan
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
